import Foundation

struct SettingsDraft: Equatable {
    var includeEvents: Bool
    var includeAllDayEvents: Bool
    var includeReminders: Bool
    var lookAheadHours: Int
    var contextualPreviewLeadMinutes: Int
    var menuBarRotationWindowMinutes: Int
    var alertLeadMinutes: Int
    var concurrentEventRotationSeconds: Int
    var maxListItems: Int
    var showAgendaSummary: Bool
    var agendaSummaryMaximumWords: Int
    var useLinkedPagePreviewsInAgendaSummary: Bool
    var enableBlinkAlert: Bool
    var menuBarFontSize: Double
    var useSimplifiedCountdown: Bool
    var activeEventDisplayMode: ActiveEventDisplayMode
    var useEventTitleEllipsis: Bool
    var eventTitleMaxCharacters: Int
    var rewriteEventTitlesWithAppleIntelligence: Bool
    var useRewrittenEventTitlesInDropdown: Bool
    var includeAstronomy: Bool
    var includeSunriseSunset: Bool
    var includeSolarNoonMidnight: Bool
    var includeMoonPhases: Bool
    var includeOrbitalHighlights: Bool
    var useAutomaticAstronomyLocation: Bool
    var astronomyColorID: String
    var astronomyLatitude: Double
    var astronomyLongitude: Double
    var selectedEventCalendarIDs: Set<String>
    var selectedReminderCalendarIDs: Set<String>
    var weekdayOnlyEventCalendarIDs: Set<String>
    var weekdayOnlyReminderCalendarIDs: Set<String>
    var calendarAlertRules: [CalendarAlertRule]
    var nonWorkingDateKeys: Set<String>
    var footballTargetCalendarID: String
    var footballAutoAddCompetitionSlugs: Set<String>
    var footballCalendarAlertOption: FootballCalendarAlertOption
    var enableFootballGoalNotifications: Bool
    var enableFootballDisallowedGoalNotifications: Bool
    var includeFootballGoalScorerInNotifications: Bool
    var enableFootballFinalNotifications: Bool
    var enableFootballAutoAddNotifications: Bool
    var showFinishedFootballMatches: Bool
    var finishedFootballMatchLookbackDays: Int
    var footballMatchLookaheadDays: Int
    var gameSaleTargetCalendarID: String
    var gameSaleCalendarAlertOption: GameSaleCalendarAlertOption
    var gameSaleAutoAddStores: Set<GameStore>
    var enableGameSaleAutoAddNotifications: Bool
    var googleHolidayCountryIDs: Set<String>
    var googleHolidayTargetCalendarID: String
    var slackStatusSyncRules: [SlackStatusSyncRule]
    var slackMeetingStatusText: String
    var slackMeetingStatusEmoji: String
    var meetingBrowserRouting: MeetingBrowserRoutingSettings

    init(settings: AppSettings) {
        includeEvents = settings.includeEvents
        includeAllDayEvents = settings.includeAllDayEvents
        includeReminders = settings.includeReminders
        lookAheadHours = settings.lookAheadHours
        contextualPreviewLeadMinutes = settings.contextualPreviewLeadMinutes
        menuBarRotationWindowMinutes = settings.menuBarRotationWindowMinutes
        alertLeadMinutes = settings.alertLeadMinutes
        concurrentEventRotationSeconds = settings.concurrentEventRotationSeconds
        maxListItems = settings.maxListItems
        showAgendaSummary = settings.showAgendaSummary
        agendaSummaryMaximumWords = settings.agendaSummaryMaximumWords
        useLinkedPagePreviewsInAgendaSummary = settings.useLinkedPagePreviewsInAgendaSummary
        enableBlinkAlert = settings.enableBlinkAlert
        menuBarFontSize = settings.menuBarFontSize
        useSimplifiedCountdown = settings.useSimplifiedCountdown
        activeEventDisplayMode = settings.activeEventDisplayMode
        useEventTitleEllipsis = settings.useEventTitleEllipsis
        eventTitleMaxCharacters = settings.eventTitleMaxCharacters
        rewriteEventTitlesWithAppleIntelligence = settings.rewriteEventTitlesWithAppleIntelligence
        useRewrittenEventTitlesInDropdown = settings.useRewrittenEventTitlesInDropdown
        includeAstronomy = settings.includeAstronomy
        includeSunriseSunset = settings.includeSunriseSunset
        includeSolarNoonMidnight = settings.includeSolarNoonMidnight
        includeMoonPhases = settings.includeMoonPhases
        includeOrbitalHighlights = settings.includeOrbitalHighlights
        useAutomaticAstronomyLocation = settings.useAutomaticAstronomyLocation
        astronomyColorID = settings.astronomyColorID
        astronomyLatitude = settings.astronomyLatitude
        astronomyLongitude = settings.astronomyLongitude
        selectedEventCalendarIDs = settings.selectedEventCalendarIDs
        selectedReminderCalendarIDs = settings.selectedReminderCalendarIDs
        weekdayOnlyEventCalendarIDs = settings.weekdayOnlyEventCalendarIDs
        weekdayOnlyReminderCalendarIDs = settings.weekdayOnlyReminderCalendarIDs
        calendarAlertRules = settings.calendarAlertRules
        nonWorkingDateKeys = settings.nonWorkingDateKeys
        footballTargetCalendarID = settings.footballTargetCalendarID
        footballAutoAddCompetitionSlugs = settings.footballAutoAddCompetitionSlugs
        footballCalendarAlertOption = settings.footballCalendarAlertOption
        enableFootballGoalNotifications = settings.enableFootballGoalNotifications
        enableFootballDisallowedGoalNotifications = settings.enableFootballDisallowedGoalNotifications
        includeFootballGoalScorerInNotifications = settings.includeFootballGoalScorerInNotifications
        enableFootballFinalNotifications = settings.enableFootballFinalNotifications
        enableFootballAutoAddNotifications = settings.enableFootballAutoAddNotifications
        showFinishedFootballMatches = settings.showFinishedFootballMatches
        finishedFootballMatchLookbackDays = settings.finishedFootballMatchLookbackDays
        footballMatchLookaheadDays = settings.footballMatchLookaheadDays
        gameSaleTargetCalendarID = settings.gameSaleTargetCalendarID
        gameSaleCalendarAlertOption = settings.gameSaleCalendarAlertOption
        gameSaleAutoAddStores = settings.gameSaleAutoAddStores
        enableGameSaleAutoAddNotifications = settings.enableGameSaleAutoAddNotifications
        googleHolidayCountryIDs = settings.googleHolidayCountryIDs
        googleHolidayTargetCalendarID = settings.googleHolidayTargetCalendarID
        slackStatusSyncRules = settings.slackStatusSyncRules
        slackMeetingStatusText = settings.slackMeetingStatusText
        slackMeetingStatusEmoji = settings.slackMeetingStatusEmoji
        meetingBrowserRouting = settings.meetingBrowserRouting
    }

    static let empty = SettingsDraft(settings: .defaults)
}
