import Foundation

enum DefaultsKeys {
    static let includeEvents = "includeEvents"
    static let includeAllDayEvents = "includeAllDayEvents"
    static let includeReminders = "includeReminders"
    static let includeAstronomy = "includeAstronomy"
    static let includeSunriseSunset = "includeSunriseSunset"
    static let includeSolarNoonMidnight = "includeSolarNoonMidnight"
    static let includeMoonPhases = "includeMoonPhases"
    static let includeOrbitalHighlights = "includeOrbitalHighlights"
    static let useAutomaticAstronomyLocation = "useAutomaticAstronomyLocation"
    static let astronomyColorID = "astronomyColorID"
    static let astronomyLatitude = "astronomyLatitude"
    static let astronomyLongitude = "astronomyLongitude"
    static let selectedEventCalendarIDs = "selectedEventCalendarIDs"
    static let selectedReminderCalendarIDs = "selectedReminderCalendarIDs"
    static let weekdayOnlyEventCalendarIDs = "weekdayOnlyEventCalendarIDs"
    static let weekdayOnlyReminderCalendarIDs = "weekdayOnlyReminderCalendarIDs"
    static let lookAheadHours = "lookAheadHours"
    static let contextualPreviewLeadMinutes = "contextualPreviewLeadMinutes"
    static let menuBarRotationWindowMinutes = "menuBarRotationWindowMinutes"
    static let alertLeadMinutes = "alertLeadMinutes"
    static let concurrentEventRotationSeconds = "concurrentEventRotationSeconds"
    static let useSimplifiedCountdown = "useSimplifiedCountdown"
    static let activeEventDisplayMode = "activeEventDisplayMode"
    static let useEventTitleEllipsis = "useEventTitleEllipsis"
    static let eventTitleMaxCharacters = "eventTitleMaxCharacters"
    static let maxListItems = "maxListItems"
    static let enableBlinkAlert = "enableBlinkAlert"
    static let menuBarFontSize = "menuBarFontSize"
    static let skippedItemKeys = "skippedItemKeys"
    static let footballTargetCalendarID = "footballTargetCalendarID"
    static let footballCalendarAlertOption = "footballCalendarAlertOption"
    static let showFinishedFootballMatches = "showFinishedFootballMatches"
    static let finishedFootballMatchLookbackDays = "finishedFootballMatchLookbackDays"
    static let footballMatchLookaheadDays = "footballMatchLookaheadDays"
    static let enableSlackMeetingStatusSync = "enableSlackMeetingStatusSync"
    static let slackMeetingCalendarID = "slackMeetingCalendarID"
    static let selectedSlackConnectionID = "selectedSlackConnectionID"
    static let slackConnections = "slackConnections"
    static let slackStatusSyncRules = "slackStatusSyncRules"
    static let slackMeetingStatusText = "slackMeetingStatusText"
    static let slackMeetingStatusEmoji = "slackMeetingStatusEmoji"
    static let managedFootballEventRecords = "managedFootballEventRecords"
    static let didAutoRecoverEmptyEventCalendarSelection = "didAutoRecoverEmptyEventCalendarSelection"
    static let didAutoRecoverEmptyReminderCalendarSelection = "didAutoRecoverEmptyReminderCalendarSelection"
}
