import Foundation

enum DefaultsKeys {
    static let includeEvents = "includeEvents"
    static let includeAllDayEvents = "includeAllDayEvents"
    static let includeReminders = "includeReminders"
    static let includeWeather = "includeWeather"
    static let includeAstronomy = "includeAstronomy"
    static let useAutomaticAstronomyLocation = "useAutomaticAstronomyLocation"
    static let astronomyColorID = "astronomyColorID"
    static let astronomyLatitude = "astronomyLatitude"
    static let astronomyLongitude = "astronomyLongitude"
    static let selectedEventCalendarIDs = "selectedEventCalendarIDs"
    static let selectedReminderCalendarIDs = "selectedReminderCalendarIDs"
    static let weekdayOnlyEventCalendarIDs = "weekdayOnlyEventCalendarIDs"
    static let weekdayOnlyReminderCalendarIDs = "weekdayOnlyReminderCalendarIDs"
    static let lookAheadHours = "lookAheadHours"
    static let alertLeadMinutes = "alertLeadMinutes"
    static let nearUpcomingAlternateMinutes = "nearUpcomingAlternateMinutes"
    static let concurrentEventRotationSeconds = "concurrentEventRotationSeconds"
    static let useSimplifiedCountdown = "useSimplifiedCountdown"
    static let activeEventDisplayMode = "activeEventDisplayMode"
    static let useEventTitleEllipsis = "useEventTitleEllipsis"
    static let eventTitleMaxCharacters = "eventTitleMaxCharacters"
    static let maxListItems = "maxListItems"
    static let enableBlinkAlert = "enableBlinkAlert"
    static let menuBarFontSize = "menuBarFontSize"
    static let skippedItemKeys = "skippedItemKeys"
    static let skippedWeatherUntil = "skippedWeatherUntil"
}
